In [14]:
import numpy as np
massiv = np.random.uniform(0, 10, [5, 5])
print(massiv)
round_mass = np.fix(massiv)
#Функция fix() округляет до ближайшего к нулю целого числа
print(round_mass)

[[5.20068734 9.28976439 8.33153194 9.11303421 3.28580811]
 [5.55686289 4.03983331 1.66522118 3.10795408 4.70770706]
 [3.56029866 2.84631811 4.95440628 8.9975507  7.66435159]
 [1.05239796 9.48933388 4.43226094 1.78391724 7.74907987]
 [7.6246333  4.01715933 2.7472071  1.39459759 2.05686441]]
[[5. 9. 8. 9. 3.]
 [5. 4. 1. 3. 4.]
 [3. 2. 4. 8. 7.]
 [1. 9. 4. 1. 7.]
 [7. 4. 2. 1. 2.]]
