In [1]:
import numpy as np
Rmatr = np.random.random((3,3,3))
#Данная функция создает массив указанной формы и заполняет его случайными числами с плавающей точкой 
print(Rmatr)

[[[0.92882534 0.68714459 0.95357272]
  [0.80427802 0.5239352  0.5781412 ]
  [0.17528913 0.0344862  0.69982994]]

 [[0.73337495 0.36231553 0.34544345]
  [0.22308164 0.16385571 0.81779244]
  [0.9079944  0.39786401 0.54647401]]

 [[0.89010566 0.88017717 0.63697332]
  [0.53841563 0.39244547 0.51496899]
  [0.69170521 0.87413542 0.91744723]]]
