In [7]:
import numpy as np
matrica = np.zeros((8,8), dtype=int)
#тип int ставим для того, чтобы в матрице стояли просто 0, а не 0.
matrica[::2,1::2] = 1
#в первой строке и в каждой через одну вниз от неё со второго элемента и через один ставим цифру 1
matrica[1::2,::2] = 1
#во второй строке и в каждой через одну вниз от неё с первого элемента и через один ставим цифру 1
print(matrica)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
