In [1]:
import numpy as np
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
# Из числа Z вычитаем остаток от деления на еденицу.
print (np.floor(Z))
#Функция floor() выполняет округление к меньшему целому числу.
print (np.ceil(Z)-1)
# Функция ceil() округляет к большему целому числу, а затем мы вычтем еденицу.
print (np.trunc(Z))
#Функция trunc() отбрасывает дробную часть числа.

 

[4. 8. 3. 4. 0. 0. 3. 2. 2. 9.]
[4. 8. 3. 4. 0. 0. 3. 2. 2. 9.]
[4. 8. 3. 4. 0. 0. 3. 2. 2. 9.]
[4. 8. 3. 4. 0. 0. 3. 2. 2. 9.]
