In [4]:
import numpy as np
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]
