In [5]:
import numpy as np
matrica_do= np.random.random((5,5))
print("Сгенерированная матрица")
print(matrica_do)
znach_max, znach_min = np.max(matrica_do), np.min(matrica_do)
matrica_posle = (matrica_do- znach_min)/(znach_max - znach_min)
print("Нормализованная матрица")
print(matrica_posle)

Сгенерированная матрица
[[0.01890032 0.57658864 0.30088983 0.05963988 0.20197334]
 [0.89522545 0.48309494 0.54344106 0.96843761 0.45909176]
 [0.18264158 0.82511523 0.31361203 0.666052   0.05029954]
 [0.72469852 0.5673892  0.63236849 0.65034946 0.46382113]
 [0.24890051 0.13958749 0.71232219 0.34261656 0.50566827]]
Нормализованная матрица
[[0.         0.58732641 0.29697571 0.04290465 0.19280235]
 [0.92289702 0.48886403 0.55241722 1.         0.46358521]
 [0.17244322 0.84906082 0.31037402 0.68154425 0.03306791]
 [0.74330751 0.57763806 0.64607065 0.66500721 0.46856592]
 [0.24222344 0.12710103 0.73027345 0.34091999 0.51263701]]
