In [5]:
import numpy as np
diagonal = np.array([1, 2, 3, 4])
matrica = np.diag(diagonal, k=-1)
#Функция np.diag(v, k) позволяет строить диагональные массивы из одномерных, v - может быть списком,
#кортежем или одномерным массивом, k - индекс диагонали.
print(matrica)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
